# Supplementary runtime and CO2 measurement, v4

This notebook runs the additive script `scripts/run_supplementary_runtime_co2_v4.py`.

The script measures one successful eligible document per method/dataset, counts the eligible documents in the JSONL file, and extrapolates the total time and CO2 indicators. It writes CSV/JSON outputs to `data/suplementary_metrics/`.

Compared with v2, this version stores compact error diagnostics and, by default, uses `--sample-strategy first-success`, which tries the next eligible document if the selected sample fails. Failed candidate samples are recorded but are not used for CO2 extrapolation.

In [2]:
%load_ext autoreload
%autoreload 2
# Run this notebook from tests/processing/. Move to the project root.
%cd ../..

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/galencarmedeiro/git/postdoc/ragtree

In [3]:
from pathlib import Path
ROOT = Path.cwd()
ROOT

PosixPath('/home/galencarmedeiro/git/postdoc/ragtree')

## List configured method/dataset runs

In [4]:
%run scripts/run_supplementary_runtime_co2_v4.py --list

Configured method/dataset runs: 57
001. LLM-only               | baseline                   | docred_causal      | filter=dev      | mode=direct_llm
002. LLM-only               | baseline                   | eventstoryline     | filter=all      | mode=direct_llm
003. LLM-only               | baseline                   | fincausal          | filter=all      | mode=direct_llm
004. LLM-only               | baseline                   | maven_ere          | filter=all      | mode=direct_llm
005. LLM-only               | baseline                   | causalbank         | filter=all      | mode=direct_llm
006. LLM-only               | cot                        | docred_causal      | filter=dev      | mode=direct_llm
007. LLM-only               | cot                        | eventstoryline     | filter=all      | mode=direct_llm
008. LLM-only               | cot                        | fincausal          | filter=all      | mode=direct_llm
009. LLM-only               | cot                        | causalbank         | filter=all      | mode=direct_llm
010. LLM-only               | cot                        | maven_ere          | filter=all      | mode=direct_llm
011. LLM-only               | icl                        | docred_causal      | filter=dev      | mode=direct_llm
012. LLM-only               | icl                        | eventstoryline     | filter=all      | mode=direct_llm
013. LLM-only               | icl                        | fincausal          | filter=all      | mode=direct_llm
014. LLM-only               | icl                        | maven_ere          | filter=all      | mode=direct_llm
015. LLM-only               | icl                        | causalbank         | filter=all      | mode=direct_llm
016. Ontology-guided RAG    | growlrag                   | docred_causal      | filter=dev      | mode=script
017. Ontology-guided RAG    | growlrag                   | eventstoryline     | filter=all      | mode=script
018. Ontology-guided RAG    | growlrag                   | causalbank         | filter=all      | mode=script
019. Ontology-guided RAG    | growlrag                   | fincausal          | filter=all      | mode=script
020. Ontology-guided RAG    | growlrag                   | maven_ere          | filter=all      | mode=script
021. Ontology-guided RAG    | ograg                      | docred_causal      | filter=dev      | mode=script
022. Ontology-guided RAG    | chunk_orag                 | docred_causal      | filter=dev      | mode=script
023. Ontology-guided RAG    | ograg                      | eventstoryline     | filter=all      | mode=script
024. Ontology-guided RAG    | chunk_orag                 | eventstoryline     | filter=all      | mode=script
025. Ontology-guided RAG    | ograg                      | causalbank         | filter=all      | mode=script
026. Ontology-guided RAG    | chunk_orag                 | causalbank         | filter=all      | mode=script
027. Ontology-guided RAG    | ograg                      | fincausal          | filter=all      | mode=script
028. Ontology-guided RAG    | chunk_orag                 | fincausal          | filter=all      | mode=script
029. Ontology-guided RAG    | ograg                      | maven_ere          | filter=all      | mode=script
030. Ontology-guided RAG    | chunk_orag                 | maven_ere          | filter=all      | mode=script
031. KG-based RAG           | kg_rag                     | docred_causal      | filter=dev      | mode=script
032. KG-based RAG           | triple_kg_rag              | docred_causal      | filter=dev      | mode=script
033. KG-based RAG           | community_kgrag            | docred_causal      | filter=dev      | mode=script
034. KG-based RAG           | kg_rag                     | eventstoryline     | filter=full     | mode=script
035. KG-based RAG           | triple_kg_rag              | eventstoryline     | filter=all      | mode=script
036. KG-based RAG           | community_kgrag            | eventstoryline     | filter=all      | mode=script
037. KG-based RAG           | kg_rag                     | fincausal          | filter=all      | mode=script
038. KG-based RAG           | triple_kg_rag              | fincausal          | filter=all      | mode=script
039. KG-based RAG           | community_kgrag            | fincausal          | filter=all      | mode=script
040. KG-based RAG           | kg_rag                     | maven_ere          | filter=all      | mode=script
041. KG-based RAG           | triple_kg_rag              | maven_ere          | filter=all      | mode=script
042. KG-based RAG           | community_kgrag            | maven_ere          | filter=all      | mode=script
043. KG-based RAG           | kg_rag                     | causalbank         | filter=all      | mode=script
044. KG-based RAG           | triple_kg_rag              | causalbank         | filter=all      | mode=script
045. KG-based RAG           | community_kgrag            | causalbank         | filter=all      | mode=script
046. Agentic RAG            | langgraph_agentic_simple   | docred_causal      | filter=dev      | mode=script
047. Agentic RAG            | agentic_hybrid             | docred_causal      | filter=dev      | mode=script
048. Agentic RAG            | langgraph_agentic_simple   | eventstoryline     | filter=all      | mode=script
049. Agentic RAG            | agentic_hybrid             | eventstoryline     | filter=all      | mode=script
050. Agentic RAG            | langgraph_agentic_simple   | fincausal          | filter=all      | mode=script
051. Agentic RAG            | agentic_hybrid             | fincausal          | filter=all      | mode=script
052. Agentic RAG            | langgraph_agentic_simple   | maven_ere          | filter=all      | mode=script
053. Agentic RAG            | agentic_hybrid             | maven_ere          | filter=all      | mode=script
054. Agentic RAG            | langgraph_agentic_simple   | causalbank         | filter=all      | mode=script
055. Agentic RAG            | agentic_hybrid             | causalbank         | filter=all      | mode=script
056. Agentic RAG            | langgraph_agentic_hybrid   | docred_causal      | filter=dev      | mode=script
057. Agentic RAG            | marag                      | docred_causal      | filter=dev      | mode=script

## Dry run

This resolves the commands and selected documents without executing the methods.

In [5]:
%run scripts/run_supplementary_runtime_co2_v4.py \
  --dry-run \
  --sample-index 0 \
  --sample-strategy first-success

[supplementary] root=/home/galencarmedeiro/git/postdoc/ragtree
[supplementary] source config=/home/galencarmedeiro/git/postdoc/ragtree/configs/default.yaml
[supplementary] runtime config=/home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_measurement_config.yaml
[supplementary] output dir=/home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics
[supplementary] selected runs=57
[supplementary] power_kw=0.3
[supplementary] carbon_intensity_kg_per_kwh=0.045
[supplementary] sample_strategy=first-success
[supplementary] max_sample_attempts=20
[1/57] LLM-only | baseline | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[2/57] LLM-only | baseline | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[3/57] LLM-only | baseline | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[4/57] LLM-only | baseline | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[5/57] LLM-only | baseline | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[6/57] LLM-only | cot | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[7/57] LLM-only | cot | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[8/57] LLM-only | cot | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[9/57] LLM-only | cot | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[10/57] LLM-only | cot | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[11/57] LLM-only | icl | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[12/57] LLM-only | icl | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[13/57] LLM-only | icl | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[14/57] LLM-only | icl | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[15/57] LLM-only | icl | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[16/57] Ontology-guided RAG | growlrag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[17/57] Ontology-guided RAG | growlrag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[18/57] Ontology-guided RAG | growlrag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[19/57] Ontology-guided RAG | growlrag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[20/57] Ontology-guided RAG | growlrag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[21/57] Ontology-guided RAG | ograg | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[22/57] Ontology-guided RAG | chunk_orag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[23/57] Ontology-guided RAG | ograg | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[24/57] Ontology-guided RAG | chunk_orag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[25/57] Ontology-guided RAG | ograg | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[26/57] Ontology-guided RAG | chunk_orag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[27/57] Ontology-guided RAG | ograg | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[28/57] Ontology-guided RAG | chunk_orag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[29/57] Ontology-guided RAG | ograg | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[30/57] Ontology-guided RAG | chunk_orag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[31/57] KG-based RAG | kg_rag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[32/57] KG-based RAG | triple_kg_rag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[33/57] KG-based RAG | community_kgrag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[34/57] KG-based RAG | kg_rag | eventstoryline | eligible=254 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[35/57] KG-based RAG | triple_kg_rag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[36/57] KG-based RAG | community_kgrag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[37/57] KG-based RAG | kg_rag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[38/57] KG-based RAG | triple_kg_rag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[39/57] KG-based RAG | community_kgrag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[40/57] KG-based RAG | kg_rag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[41/57] KG-based RAG | triple_kg_rag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[42/57] KG-based RAG | community_kgrag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[43/57] KG-based RAG | kg_rag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[44/57] KG-based RAG | triple_kg_rag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[45/57] KG-based RAG | community_kgrag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[46/57] Agentic RAG | langgraph_agentic_simple | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[47/57] Agentic RAG | agentic_hybrid | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[48/57] Agentic RAG | langgraph_agentic_simple | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[49/57] Agentic RAG | agentic_hybrid | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> DRY-RUN: command resolved but not executed.
[50/57] Agentic RAG | langgraph_agentic_simple | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[51/57] Agentic RAG | agentic_hybrid | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> DRY-RUN: command resolved but not executed.
[52/57] Agentic RAG | langgraph_agentic_simple | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[53/57] Agentic RAG | agentic_hybrid | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> DRY-RUN: command resolved but not executed.
[54/57] Agentic RAG | langgraph_agentic_simple | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[55/57] Agentic RAG | agentic_hybrid | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> DRY-RUN: command resolved but not executed.
[56/57] Agentic RAG | langgraph_agentic_hybrid | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[57/57] Agentic RAG | marag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> DRY-RUN: command resolved but not executed.
[supplementary] wrote:
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_by_method_dataset.csv
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_by_method_dataset.json
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_latex_rows.txt
  - logs: /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/logs

## Single-run test

Use this before launching all 57 runs. If the first document fails, v4 will try subsequent eligible documents up to `--max-sample-attempts`.

In [7]:
%run scripts/run_supplementary_runtime_co2_v4.py \
  --only-method baseline \
  --only-dataset docred_causal \
  --sample-index 0 \
  --sample-strategy first-success \
  --max-sample-attempts 20 \
  --power-kw 0.300 \
  --carbon-intensity 0.045 \
  --show-error-tail 80

[supplementary] root=/home/galencarmedeiro/git/postdoc/ragtree
[supplementary] source config=/home/galencarmedeiro/git/postdoc/ragtree/configs/default.yaml
[supplementary] runtime config=/home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_measurement_config.yaml
[supplementary] output dir=/home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics
[supplementary] selected runs=1
[supplementary] power_kw=0.3
[supplementary] carbon_intensity_kg_per_kwh=0.045
[supplementary] sample_strategy=first-success
[supplementary] max_sample_attempts=20
[supplementary] vLLM preflight reached http://localhost:8000/v1/models with status 200.
[1/1] LLM-only | baseline | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=14.55s, estimated_total=242.09min, estimated_total_co2=54.4691g
[supplementary] wrote:
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_by_method_dataset.csv
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_by_method_dataset.json
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_latex_rows.txt
  - logs: /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/logs

## Run all method/dataset configurations

Run this after the single-run test succeeds.

In [8]:
%run scripts/run_supplementary_runtime_co2_v4.py \
  --sample-index 0 \
  --sample-strategy first-success \
  --max-sample-attempts 20 \
  --power-kw 0.300 \
  --carbon-intensity 0.045 \
  --show-error-tail 40

[supplementary] root=/home/galencarmedeiro/git/postdoc/ragtree
[supplementary] source config=/home/galencarmedeiro/git/postdoc/ragtree/configs/default.yaml
[supplementary] runtime config=/home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_measurement_config.yaml
[supplementary] output dir=/home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics
[supplementary] selected runs=57
[supplementary] power_kw=0.3
[supplementary] carbon_intensity_kg_per_kwh=0.045
[supplementary] sample_strategy=first-success
[supplementary] max_sample_attempts=20
[supplementary] vLLM preflight reached http://localhost:8000/v1/models with status 200.
[1/57] LLM-only | baseline | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=11.39s, estimated_total=189.39min, estimated_total_co2=42.6139g
[2/57] LLM-only | baseline | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=14.94s, estimated_total=110.29min, estimated_total_co2=24.8156g
[3/57] LLM-only | baseline | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=0.27s, estimated_total=4.41min, estimated_total_co2=0.9916g
[4/57] LLM-only | baseline | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=15.48s, estimated_total=907.27min, estimated_total_co2=204.1349g
[5/57] LLM-only | baseline | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=4.47s, estimated_total=80.40min, estimated_total_co2=18.0908g
[6/57] LLM-only | cot | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=50.10s, estimated_total=833.30min, estimated_total_co2=187.4928g
[7/57] LLM-only | cot | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=57.33s, estimated_total=423.27min, estimated_total_co2=95.2353g
[8/57] LLM-only | cot | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=10.72s, estimated_total=172.71min, estimated_total_co2=38.8604g
[9/57] LLM-only | cot | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=13.81s, estimated_total=248.57min, estimated_total_co2=55.9276g
[10/57] LLM-only | cot | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=63.64s, estimated_total=3729.10min, estimated_total_co2=839.0477g
[11/57] LLM-only | icl | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=16.65s, estimated_total=276.95min, estimated_total_co2=62.3140g
[12/57] LLM-only | icl | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=15.56s, estimated_total=114.90min, estimated_total_co2=25.8532g
[13/57] LLM-only | icl | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=0.28s, estimated_total=4.58min, estimated_total_co2=1.0303g
[14/57] LLM-only | icl | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=12.02s, estimated_total=704.26min, estimated_total_co2=158.4595g
[15/57] LLM-only | icl | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=5.61s, estimated_total=100.94min, estimated_total_co2=22.7115g
[16/57] Ontology-guided RAG | growlrag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=32.26s, estimated_total=536.56min, estimated_total_co2=120.7265g
[17/57] Ontology-guided RAG | growlrag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=23.80s, estimated_total=175.71min, estimated_total_co2=39.5355g
[18/57] Ontology-guided RAG | growlrag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=9.86s, estimated_total=177.41min, estimated_total_co2=39.9173g
[19/57] Ontology-guided RAG | growlrag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=1.16s, estimated_total=18.71min, estimated_total_co2=4.2094g
[20/57] Ontology-guided RAG | growlrag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=12.79s, estimated_total=749.28min, estimated_total_co2=168.5877g
[21/57] Ontology-guided RAG | ograg | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=7.38s, estimated_total=122.74min, estimated_total_co2=27.6156g
[22/57] Ontology-guided RAG | chunk_orag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=50.24s, estimated_total=835.66min, estimated_total_co2=188.0226g
[23/57] Ontology-guided RAG | ograg | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=11.22s, estimated_total=82.88min, estimated_total_co2=18.6469g
[24/57] Ontology-guided RAG | chunk_orag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=38.16s, estimated_total=281.73min, estimated_total_co2=63.3895g
[25/57] Ontology-guided RAG | ograg | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=7.08s, estimated_total=127.50min, estimated_total_co2=28.6865g
[26/57] Ontology-guided RAG | chunk_orag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=15.38s, estimated_total=276.81min, estimated_total_co2=62.2822g
[27/57] Ontology-guided RAG | ograg | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=1.12s, estimated_total=17.98min, estimated_total_co2=4.0461g
[28/57] Ontology-guided RAG | chunk_orag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=7.73s, estimated_total=124.64min, estimated_total_co2=28.0429g
[29/57] Ontology-guided RAG | ograg | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=14.66s, estimated_total=858.91min, estimated_total_co2=193.2556g
[30/57] Ontology-guided RAG | chunk_orag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=16.36s, estimated_total=958.76min, estimated_total_co2=215.7216g
[31/57] KG-based RAG | kg_rag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=22.73s, estimated_total=378.02min, estimated_total_co2=85.0556g
[32/57] KG-based RAG | triple_kg_rag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=16.67s, estimated_total=277.25min, estimated_total_co2=62.3817g
[33/57] KG-based RAG | community_kgrag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=27.20s, estimated_total=452.36min, estimated_total_co2=101.7805g
[34/57] KG-based RAG | kg_rag | eventstoryline | eligible=254 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=22.05s, estimated_total=93.35min, estimated_total_co2=21.0037g
[35/57] KG-based RAG | triple_kg_rag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=13.28s, estimated_total=98.07min, estimated_total_co2=22.0660g
[36/57] KG-based RAG | community_kgrag | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=20.35s, estimated_total=150.22min, estimated_total_co2=33.8005g
[37/57] KG-based RAG | kg_rag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=1.62s, estimated_total=26.10min, estimated_total_co2=5.8725g
[38/57] KG-based RAG | triple_kg_rag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=0.89s, estimated_total=14.35min, estimated_total_co2=3.2279g
[39/57] KG-based RAG | community_kgrag | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=11.26s, estimated_total=181.43min, estimated_total_co2=40.8210g
[40/57] KG-based RAG | kg_rag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=9.94s, estimated_total=582.30min, estimated_total_co2=131.0172g
[41/57] KG-based RAG | triple_kg_rag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=14.78s, estimated_total=866.35min, estimated_total_co2=194.9279g
[42/57] KG-based RAG | community_kgrag | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=21.71s, estimated_total=1272.06min, estimated_total_co2=286.2145g
[43/57] KG-based RAG | kg_rag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=49.88s, estimated_total=897.88min, estimated_total_co2=202.0237g
[44/57] KG-based RAG | triple_kg_rag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=3.55s, estimated_total=63.94min, estimated_total_co2=14.3856g
[45/57] KG-based RAG | community_kgrag | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=16.44s, estimated_total=295.85min, estimated_total_co2=66.5662g
[46/57] Agentic RAG | langgraph_agentic_simple | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=19.87s, estimated_total=330.56min, estimated_total_co2=74.3766g
[47/57] Agentic RAG | agentic_hybrid | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=23.28s, estimated_total=387.19min, estimated_total_co2=87.1180g
[48/57] Agentic RAG | langgraph_agentic_simple | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=15.18s, estimated_total=112.06min, estimated_total_co2=25.2146g
[49/57] Agentic RAG | agentic_hybrid | eventstoryline | eligible=443 | sample_skip=0 | doc_id=EventStoryLine - 1_10ecbplus
    -> OK: elapsed=70.03s, estimated_total=517.02min, estimated_total_co2=116.3304g
[50/57] Agentic RAG | langgraph_agentic_simple | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=0.98s, estimated_total=15.75min, estimated_total_co2=3.5434g
[51/57] Agentic RAG | agentic_hybrid | fincausal | eligible=967 | sample_skip=0 | doc_id=FinCausal - bfdb8bd54bcc5044
    -> OK: elapsed=1.20s, estimated_total=19.36min, estimated_total_co2=4.3558g
[52/57] Agentic RAG | langgraph_agentic_simple | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=44.96s, estimated_total=2634.72min, estimated_total_co2=592.8127g
[53/57] Agentic RAG | agentic_hybrid | maven_ere | eligible=3516 | sample_skip=0 | doc_id=MAVEN_ERE - 2002c29914e6d8b5
    -> OK: elapsed=14.20s, estimated_total=832.24min, estimated_total_co2=187.2549g
[54/57] Agentic RAG | langgraph_agentic_simple | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=53.39s, estimated_total=961.02min, estimated_total_co2=216.2301g
[55/57] Agentic RAG | agentic_hybrid | causalbank | eligible=1080 | sample_skip=0 | doc_id=CausalBank - e324949663db4295
    -> OK: elapsed=89.50s, estimated_total=1611.07min, estimated_total_co2=362.4909g
[56/57] Agentic RAG | langgraph_agentic_hybrid | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=40.97s, estimated_total=681.45min, estimated_total_co2=153.3272g
[57/57] Agentic RAG | marag | docred_causal | eligible=998 | sample_skip=0 | doc_id=DocRED - e37288ca6012859f
    -> OK: elapsed=20.06s, estimated_total=333.60min, estimated_total_co2=75.0593g
[supplementary] wrote:
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_by_method_dataset.csv
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_by_method_dataset.json
  - /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/runtime_co2_latex_rows.txt
  - logs: /home/galencarmedeiro/git/postdoc/ragtree/data/suplementary_metrics/logs

## Read the generated CSV

In [9]:
import pandas as pd
from pathlib import Path
path = Path('data/suplementary_metrics/runtime_co2_by_method_dataset.csv')
df = pd.read_csv(path)
df.head()

,status,dry_run,success,return_code,error,error_type,error_message,error_traceback_tail,method_family,method,...,elapsed_minutes_doc,energy_kwh_doc,co2_kg_doc,co2_g_doc,estimated_total_seconds,estimated_total_minutes,estimated_total_hours,estimated_total_energy_kwh,estimated_total_co2_kg,estimated_total_co2_g
0,OK,False,True,0,NaN,NaN,NaN,NaN,LLM-only,baseline,...,0.189775,0.000949,0.000043,0.042699,11363.698261,189.394971,3.156583,0.946975,0.042614,42.613868
1,OK,False,True,0,NaN,NaN,NaN,NaN,LLM-only,baseline,...,0.248965,0.001245,0.000056,0.056017,6617.495126,110.291585,1.838193,0.551458,0.024816,24.815607
2,OK,False,True,0,NaN,NaN,NaN,NaN,LLM-only,baseline,...,0.004558,0.000023,0.000001,0.001025,264.434777,4.407246,0.073454,0.022036,0.000992,0.991630
3,OK,False,True,0,NaN,NaN,NaN,NaN,LLM-only,baseline,...,0.258039,0.001290,0.000058,0.058059,54435.960198,907.266003,15.121100,4.536330,0.204135,204.134851
4,OK,False,True,0,NaN,NaN,NaN,NaN,LLM-only,baseline,...,0.074448,0.000372,0.000017,0.016751,4824.209151,80.403486,1.340058,0.402017,0.018091,18.090784

In [10]:
cols = [
    'status', 'method_family', 'method', 'dataset', 'n_eligible_documents',
    'sample_index_effective', 'attempts', 'elapsed_seconds_doc',
    'estimated_total_minutes', 'estimated_total_co2_g',
    'error_type', 'error_message'
]
df[[c for c in cols if c in df.columns]]

,status,method_family,method,dataset,n_eligible_documents,sample_index_effective,attempts,elapsed_seconds_doc,estimated_total_minutes,estimated_total_co2_g,error_type,error_message
0,OK,LLM-only,baseline,docred_causal,998,0,1,11.386471,189.394971,42.613868,NaN,NaN
1,OK,LLM-only,baseline,eventstoryline,443,0,1,14.937912,110.291585,24.815607,NaN,NaN
2,OK,LLM-only,baseline,fincausal,967,0,1,0.273459,4.407246,0.991630,NaN,NaN
3,OK,LLM-only,baseline,maven_ere,3516,0,1,15.482355,907.266003,204.134851,NaN,NaN
4,OK,LLM-only,baseline,causalbank,1080,0,1,4.466860,80.403486,18.090784,NaN,NaN
5,OK,LLM-only,cot,docred_causal,998,0,1,50.098290,833.301549,187.492849,NaN,NaN
6,OK,LLM-only,cot,eventstoryline,443,0,1,57.327473,423.267845,95.235265,NaN,NaN
7,OK,LLM-only,cot,fincausal,967,0,1,10.716403,172.712695,38.860356,NaN,NaN
8,OK,LLM-only,cot,causalbank,1080,0,1,13.809294,248.567286,55.927639,NaN,NaN
9,OK,LLM-only,cot,maven_ere,3516,0,1,63.636531,3729.100716,839.047661,NaN,NaN
10,OK,LLM-only,icl,docred_causal,998,0,1,16.650367,276.951108,62.313999,NaN,NaN
11,OK,LLM-only,icl,eventstoryline,443,0,1,15.562479,114.902974,25.853169,NaN,NaN
12,OK,LLM-only,icl,fincausal,967,0,1,0.284112,4.578945,1.030263,NaN,NaN
13,OK,LLM-only,icl,maven_ere,3516,0,1,12.018164,704.264412,158.459493,NaN,NaN
14,OK,LLM-only,icl,causalbank,1080,0,1,5.607779,100.940028,22.711506,NaN,NaN
15,OK,Ontology-guided RAG,growlrag,docred_causal,998,0,1,32.258237,536.562010,120.726452,NaN,NaN
16,OK,Ontology-guided RAG,growlrag,eventstoryline,443,0,1,23.798650,175.713367,39.535508,NaN,NaN
17,OK,Ontology-guided RAG,growlrag,causalbank,1080,0,1,9.856135,177.410432,39.917347,NaN,NaN
18,OK,Ontology-guided RAG,growlrag,fincausal,967,0,1,1.160823,18.708603,4.209436,NaN,NaN
19,OK,Ontology-guided RAG,growlrag,maven_ere,3516,0,1,12.786322,749.278486,168.587659,NaN,NaN
20,OK,Ontology-guided RAG,ograg,docred_causal,998,0,1,7.378921,122.736060,27.615614,NaN,NaN
21,OK,Ontology-guided RAG,chunk_orag,docred_causal,998,0,1,50.239851,835.656186,188.022642,NaN,NaN
22,OK,Ontology-guided RAG,ograg,eventstoryline,443,0,1,11.224645,82.875297,18.646942,NaN,NaN
23,OK,Ontology-guided RAG,chunk_orag,eventstoryline,443,0,1,38.157705,281.731055,63.389487,NaN,NaN
24,OK,Ontology-guided RAG,ograg,causalbank,1080,0,1,7.083075,127.495345,28.686453,NaN,NaN
25,OK,Ontology-guided RAG,chunk_orag,causalbank,1080,0,1,15.378328,276.809901,62.282228,NaN,NaN
26,OK,Ontology-guided RAG,ograg,fincausal,967,0,1,1.115779,17.982641,4.046094,NaN,NaN
27,OK,Ontology-guided RAG,chunk_orag,fincausal,967,0,1,7.733309,124.635158,28.042911,NaN,NaN
28,OK,Ontology-guided RAG,ograg,maven_ere,3516,0,1,14.657231,858.913717,193.255586,NaN,NaN
29,OK,Ontology-guided RAG,chunk_orag,maven_ere,3516,0,1,16.361138,958.762687,215.721605,NaN,NaN
30,OK,KG-based RAG,kg_rag,docred_causal,998,0,1,22.726939,378.024760,85.055571,NaN,NaN
31,OK,KG-based RAG,triple_kg_rag,docred_causal,998,0,1,16.668452,277.251916,62.381681,NaN,NaN
32,OK,KG-based RAG,community_kgrag,docred_causal,998,0,1,27.195866,452.357901,101.780528,NaN,NaN
33,OK,KG-based RAG,kg_rag,eventstoryline,254,0,1,22.051124,93.349758,21.003695,NaN,NaN
34,OK,KG-based RAG,triple_kg_rag,eventstoryline,443,0,1,13.282761,98.071054,22.065987,NaN,NaN
35,OK,KG-based RAG,community_kgrag,eventstoryline,443,0,1,20.346424,150.224433,33.800497,NaN,NaN
36,OK,KG-based RAG,kg_rag,fincausal,967,0,1,1.619445,26.100055,5.872512,NaN,NaN
37,OK,KG-based RAG,triple_kg_rag,fincausal,967,0,1,0.890150,14.346249,3.227906,NaN,NaN
38,OK,KG-based RAG,community_kgrag,fincausal,967,0,1,11.257079,181.426590,40.820983,NaN,NaN
39,OK,KG-based RAG,kg_rag,maven_ere,3516,0,1,9.936837,582.298628,131.017191,NaN,NaN
40,OK,KG-based RAG,triple_kg_rag,maven_ere,3516,0,1,14.784065,866.346212,194.927898,NaN,NaN
41,OK,KG-based RAG,community_kgrag,maven_ere,3516,0,1,21.707583,1272.064339,286.214476,NaN,NaN
42,OK,KG-based RAG,kg_rag,causalbank,1080,0,1,49.882397,897.883154,202.023710,NaN,NaN
43,OK,KG-based RAG,triple_kg_rag,causalbank,1080,0,1,3.551991,63.935846,14.385565,NaN,NaN
44,OK,KG-based RAG,community_kgrag,causalbank,1080,0,1,16.436092,295.849649,66.566171,NaN,NaN
45,OK,Agentic RAG,langgraph_agentic_simple,docred_causal,998,0,1,19.873518,330.562851,74.376641,NaN,NaN
46,OK,Agentic RAG,agentic_hybrid,docred_causal,998,0,1,23.278015,387.190978,87.117970,NaN,NaN
47,OK,Agentic RAG,langgraph_agentic_simple,eventstoryline,443,0,1,15.178081,112.064833,25.214588,NaN,NaN
48,OK,Agentic RAG,agentic_hybrid,eventstoryline,443,0,1,70.025829,517.024039,116.330409,NaN,NaN
49,OK,Agentic RAG,langgraph_agentic_simple,fincausal,967,0,1,0.977164,15.748620,3.543440,NaN,NaN
50,OK,Agentic RAG,agentic_hybrid,fincausal,967,0,1,1.201190,19.359184,4.355816,NaN,NaN
51,OK,Agentic RAG,langgraph_agentic_simple,maven_ere,3516,0,1,44.961147,2634.723235,592.812728,NaN,NaN
52,OK,Agentic RAG,agentic_hybrid,maven_ere,3516,0,1,14.202116,832.243990,187.254898,NaN,NaN
53,OK,Agentic RAG,langgraph_agentic_simple,causalbank,1080,0,1,53.390159,961.022866,216.230145,NaN,NaN
54,OK,Agentic RAG,agentic_hybrid,causalbank,1080,0,1,89.503926,1611.070660,362.490899,NaN,NaN
55,OK,Agentic RAG,langgraph_agentic_hybrid,docred_causal,998,0,1,40.969180,681.454019,153.327154,NaN,NaN
56,OK,Agentic RAG,marag,docred_causal,998,0,1,20.055913,333.596687,75.059255,NaN,NaN